# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0003_auto_20160604_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=300, verbose_name='first name')),
                ('last_name', models.CharField(max_length=350, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.Exam', verbose_name='exam')),
                ('replies', models.ManyToManyField(to='exams.Answer', verbose_name='replies')),
            ],
        ),
    ]
