# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=0, verbose_name='correct answer'),
        ),
    ]
