# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(default='Test', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='strict',
            field=models.BooleanField(default=1, verbose_name='stricted corretion'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=1, verbose_name='correct answer'),
        ),
    ]
