# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='snippet',
            field=models.TextField(null=True, verbose_name='snippet'),
        ),
    ]
