# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_question_snippet_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.Subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='snippet',
            field=models.TextField(blank=True, null=True, verbose_name='snippet'),
        ),
        migrations.AlterField(
            model_name='question',
            name='snippet_language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript')], max_length=200, null=True, verbose_name='snippet language'),
        ),
    ]
